"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
properties:
  web:
    type: "object"
    properties:
      port:
        type: "number"
      host:
        type: "string"
  twilio:
    type: "object"
    properties:
      accountSid:
        type: "string"
      authToken:
        type: "string"
  bridge:
    type: "object"
    properties:
      phoneNumber:
        type: "string"
      allowedUsers:
        type: "array"
  homeserver:
    type: "object"
    properties:
      domain:
        type: "string"
      url:
        type: "string"
      mediaUrl:
        type: "string"
  bot:
    type: "object"
    properties:
      appearance:
        type: "object"
        properties:
          displayName:
            type: "string"
          avatarUrl:
            type: "string"
  advanced:
    type: "object"
    properties:
      localpartPrefix:
        type: "string"
  logging:
    type: "object"
    properties:
      file:
        type: "string"
      console:
        type: "boolean"
      consoleLevel:
        type: "string"
      fileLevel:
        type: "string"
      rotate:
        type: "object"
        properties:
          size:
            type: "number"
          count:
            type: "number"